// The eatery-nod FireBase App Configuration (a PRIVATE RESOURCE in a gitignored resource)
// NOTE: We encode sensitive credential keys to alleviate exposure on deployment site!
export default 'theireyJhcGlLZXkiOiJBSXphU3lDZmpPMXNvUDFBOThLVnlsQ2JyRC11M2ROVGx1ZWdhM0UiLCJhdXRoRG9tYWluIjoiZWF0ZXJ5LW5vZC5maXJlYmFzZWFwcC5jb20iLCJkYXRhYmFzZVVSTCI6Imh0dHBzOi8vZWF0ZXJ5LW5vZC5maXJlYmFzZWlvLmNvbSIsInByb2plY3RJZCI6ImVhdGVyeS1ub2QiLCJzdG9yYWdlQnVja2V0IjoiZWF0ZXJ5LW5vZC5hcHBzcG90LmNvbSIsIm1lc3NhZ2luZ1NlbmRlcklkIjoiMTIzNjg3ODQzNzM2In0=';
